apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: messaging-api-autoscaler
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: messaging-api
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 50